### PR TITLE
Support DataJoint 2.x attribute-type spellings (backward compatible with 0.14.x)

### PR DESCRIPTION
**Pull request by akshay-jaggi**
One attribute-type spelling used by this element was removed or changed in
DataJoint 2.x. It has a replacement that works identically on 0.14.x, so this can
go in without waiting on a full 2.x migration.

### Why now

DataJoint **2.0.0** shipped 2026-02-03 and 2.3.2 is current. `install_requires`
here says `datajoint>=0.13`, so a fresh install today resolves 2.x and the
element cannot even be imported:

```
>>> import element_session.session_with_datetime
AttributeError: module 'datajoint' has no attribute 'schema'. Did you mean: 'Schema'?
  element_session/session_with_datetime.py:5   schema = dj.schema()
```

### What this changes

- `schema = dj.schema()` in `session_with_datetime.py` and `session_with_id.py`

| construct | 0.14.9 | 2.3.2 |
|---|---|---|
| `dj.schema` → `dj.Schema` | works — **literally the same object** in 0.14.9 | required; `AttributeError` at import |

Verified by activating the element against MySQL under datajoint 0.14.9 and
2.3.2 in turn.

### What this deliberately does not change

`longblob`. It also has to change for 2.x — and much more urgently, because
under 2.x a `longblob` attribute silently stores `str(array)` rather than the
array — but `<blob>` is rejected by 0.14.9, so shipping it here would break
current users. It is on a separate branch and written up in the accompanying issue.

Applied mechanically with regexes rather than typed by hand, then reviewed. No
behaviour is changed, only spellings. Happy to reshape or split this however you
prefer.

### CODE REVIEW

**Comment by dimitri-yatsenko** [comment]
Thanks for this, and for the report in #43 — the diagnosis there is correct.
I traced it upstream and filed the DataJoint-side half as
https://github.com/datajoint/datajoint-python/issues/1527.

I'd like to redirect this PR rather than merge it.

**We are not keeping elements working on both 0.14.x and 2.x.** A schema is either
2.x or pre-2.x, the two are not interoperable, DataJoint no longer supports pre-2.x,
and all schemas should be migrated. So the constraint that kept `<blob>` off this
branch does not apply — please send the full migration as a single PR instead.

There is no other 2.x failure in this element to act as a backstop. After this PR it
declares cleanly under 2.x and its 2 `longblob` attributes silently corrupt on insert.
The import error you removed is the only thing currently preventing that.

### Remaining work for the full PR

| | count | |
|---|---|---|
| `longblob` → `<blob>` | 2 | the data-loss fix |
| `int` / `smallint` → `int32` / `int16` | 2 | works today, but native; warns |

Also raise the DataJoint floor — `requirements.txt` `datajoint>=0.13.0` → `datajoint>=2.3`. That unpinned floor is
the root cause: it is what makes a fresh install resolve 2.x in the first place.

Please work from the migration guide rather than from this comment — it is the
authoritative version: **[Migrate to DataJoint 2.0](https://docs.datajoint.com/how-to/migrate-to-v20/)**.
It covers the legacy → 2.0 type mapping (`longblob` → `<blob>`, `attach` → `<attach>`,
and the `@store` variants), the `:<blob>:` column-comment marker that is the mechanism
behind the bug, the four-phase structure, and the case for creating tests before
migrating. What you have on your branch is Phase I — code only, against empty `_v2`
schemas, no impact on existing data. Migrating existing data is Phase III and separate.

There is no `tests/` directory here and CI runs `black` and `flake8` only, so your
manual verification is the only check that ran and nothing will catch a regression later.

Happy to review the full 2.x PR as soon as you open it. I'd suggest closing this one in
favour of that, or reusing this branch and pushing the rest onto it — your call, leaving
it open for you to decide.
